name: Hardcoded Newline Scan

on: [ push ]

jobs:
  check-newlines:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15.2'
      - run: go get github.com/boljen/java-hardcoded-newline-scan
      - run: java-hardcoded-newline-scan
