name: Hardcoded Newline Check

on: [ push ]

jobs:
  check-newlines:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15.2' # The Go version to download (if necessary) and use.
      - run: go get github.com/boljen/java-hardcoded-linefeed-scan
      - run: java-hardcoded-linefeed-scan
